### ISSUE TITLE
Build success? But no recovery.img

### ISSUE THREAD

**Issue by LostOuija** [lazycodebuilder/Lazy_Action-Recoverys-Builder#5]
I forked the repository and ran the action using my device tree, and it appears successful. But in the releases page there is only source, no recovery.img

**Comment by lazycodebuilder** [comment]
it's not the builder issue, make sure your device tree codes is current and build as bootimg not as recoveryimg

https://github.com/LostOuija/Lazy_Action-Recoverys-Builder/actions/runs/10002590384/job/27648133814#step:3:15

https://github.com/LostOuija/Lazy_Action-Recoverys-Builder/actions/runs/10002590384/job/27648133814#step:15:405

https://github.com/LostOuija/stylo/blob/39f4cbbfe11d3b250fd3d0b75d17a115160ed681/BoardConfig.mk#L19

**Comment by LostOuija** [comment]
Okay I ran it as boot, and I get a boot.img a ramdisk_recovery.img and a recovery.cpio file. Am I suppose to use the ramdisk_recovery.img for twrp then?

**Comment by lazycodebuilder** [comment]
you can use boot.img as twrp and please stop twrp development questions here, find twrp group they can help you.
